from enum import Enum, IntFlag, auto
from pygame.locals import (
    MOUSEBUTTONDOWN,
    MOUSEBUTTONUP,
    MOUSEMOTION,

    BUTTON_LEFT,
    BUTTON_MIDDLE,
    BUTTON_RIGHT,
    BUTTON_WHEELDOWN,
    BUTTON_WHEELUP,
)

MARGIN = 10
KMOD_BASE = 4096


class MouseEvents(Enum):
    # Mouse events
    LEFT_MOUSE_UP = MOUSEBUTTONUP, BUTTON_LEFT
    MIDDLE_MOUSE_UP = MOUSEBUTTONUP, BUTTON_MIDDLE
    RIGHT_MOUSE_UP = MOUSEBUTTONUP, BUTTON_RIGHT
    SCROLL_MOUSE_UP = MOUSEBUTTONUP, BUTTON_WHEELDOWN
    _SCROLL_MOUSE_UP = MOUSEBUTTONUP, BUTTON_WHEELUP

    LEFT_MOUSE_DOWN = MOUSEBUTTONDOWN, BUTTON_LEFT
    MIDDLE_MOUSE_DOWN = MOUSEBUTTONDOWN, BUTTON_MIDDLE
    RIGHT_MOUSE_DOWN = MOUSEBUTTONDOWN, BUTTON_RIGHT
    _SCROLL_MOUSE_DOWN = MOUSEBUTTONDOWN, BUTTON_WHEELDOWN
    SCROLL_MOUSE_DOWN = MOUSEBUTTONDOWN, BUTTON_WHEELUP

    MOVE_MOUSE = (MOUSEMOTION,)


class Alignment(IntFlag):
    # x alignments
    LEFT = auto()
    CENTRE = auto()
    RIGHT = auto()

    # y alignments
    TOP = auto()
    # CENTRE = auto()
    BOTTOM = auto()
